services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    # No external ports exposed - only accessible via nginx proxy
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SCRYFALL_DATA_DIR=/app/data/scryfall
    volumes:
      - scryfall-cache:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: mtg-proxy-print

volumes:
  scryfall-cache: